ECommerce/Controllers/AddToCartController.cs
using ECommerce.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Controllers
{
    public class AddToCartController : Controller
    {
        DataTable dt;
        ProductDAL productDAL = new ProductDAL();
        public ActionResult Add(shopping shopping)
        {
            if (Session["cart"] == null)
            {
                List<shopping> li = new List<shopping>();

                li.Add(shopping);
                Session["cart"] = li;
                ViewBag.cart = li.Count();

                Session["count"] = 1;
            }
            else
            {
                List<shopping> li = (List<shopping>)Session["cart"];
                li.Add(shopping);
                Session["cart"] = li;
                ViewBag.cart = li.Count();
                Session["count"] = Convert.ToInt32(Session["count"]) + 1;
            }
            return RedirectToAction("Home", "Site");
        }

        public ActionResult Myorder()
        {
            return View((List<shopping>)Session["cart"]);
        }

        public ActionResult Checkout()
        {
            return View();
        }
    }
}

ECommerce/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ECommerce/Controllers/SiteController.cs
using ECommerce.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Controllers
{
    public class SiteController : Controller
    {
        ShoppingPage shoppingPage = new ShoppingPage();
        // GET: Site/Home
        public ActionResult Home(shopping Shopping)
        {
            ShoppingPage shoppingPage = new ShoppingPage();

            List<shopping> shoppinglist = new List<shopping>();
            var GetProducts = shoppingPage.GetAllProducts();
            for (int i = 0; i < GetProducts.Rows.Count; i++)
            {
                shopping shopping = new shopping();
                shopping.ID = Convert.ToInt32(GetProducts.Rows[i]["ID"]);
                shopping.Product = Convert.ToString(GetProducts.Rows[i]["Product"]);
                shopping.ProductID = Convert.ToInt32(GetProducts.Rows[i]["ProductID"]);
                shopping.Cost = Convert.ToInt32(GetProducts.Rows[i]["Cost"]);
                shopping.Category = Convert.ToString(GetProducts.Rows[i]["Category"]);
                shopping.Image = Convert.ToString(GetProducts.Rows[i]["Image"]);
                shopping.Description = Convert.ToString(GetProducts.Rows[i]["Description"]);

                shoppinglist.Add(shopping);
            }
            return View(shoppinglist);
        }

        public ActionResult Clothing(int? id)
        {
            ShoppingPage shoppingPage = new ShoppingPage();
            if (id == null)
            {
                return HttpNotFound();
            }
            shopping shopping = shoppingPage.GetProductById(id);

            if (shopping == null)
            {
                return HttpNotFound();
            }
            return View(shopping);
        }

        public ActionResult AddProduct()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddProduct(shopping Shopping, HttpPostedFileBase file)
        {
            string constr = ConfigurationManager.ConnectionStrings["EComm"].ConnectionString;
            SqlConnection con = new SqlConnection(constr);
            string sqlquery = "insert into [dbo].[shopping] (Product, ProductID, Cost, Category, Image, Description) VALUES (@Product, @ProductID, @Cost, @Category, @Image, @Description)";
            SqlCommand com = new SqlCommand(sqlquery, con);
            con.Open();
            com.Parameters.AddWithValue("@Product", Shopping.Product);
            com.Parameters.AddWithValue("@ProductID", Shopping.ProductID);
            com.Parameters.AddWithValue("@Cost", Shopping.Cost);
            com.Parameters.AddWithValue("@Category", Shopping.Category);

            if (file != null && file.ContentLength > 0)
            {
                string filename = Path.GetFileName(file.FileName);
                string imgpath = Path.Combine(Server.MapPath("~/Product-Images"), filename);
                file.SaveAs(imgpath);
            }
            com.Parameters.AddWithValue("@Image", "/Product-Images/" + file.FileName);

            com.Parameters.AddWithValue("@Description", Shopping.Description);
            com.ExecuteNonQuery();
            con.Close();
            ViewData["Message"] = "Product " + Shopping.Product + " is added successfully";
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(users users)
        {
            string maincon = ConfigurationManager.ConnectionStrings["EComm"].ConnectionString;
            SqlConnection sqlcon = new SqlConnection(maincon);
            string sqlquery = "select * from users where UserName=@UserName and Password=@Password";
            sqlcon.Open();
            SqlCommand sqlcom = new SqlCommand(sqlquery, sqlcon);

            SqlParameter usernameparam = sqlcom.Parameters.AddWithValue("@UserName", users.UserName);
            if (users.UserName == null)
            {
                usernameparam.Value = DBNull.Value;
            }

            SqlParameter passwordparam = sqlcom.Parameters.AddWithValue("@Password", users.Password);
            if (users.Password == null)
            {
                passwordparam.Value = DBNull.Value;
            }
            SqlDataReader sdr = sqlcom.ExecuteReader();
            if (sdr.Read())
            {
                return RedirectToAction("Home");
            }
            else
            {
                ViewData["Msg"] = "Enter a Valid UserName and Password";
            }
            sqlcon.Close();
            return View();
        }


        public ActionResult Registration()
        {
            users obj = new users();
            obj.RoleList = shoppingPage.UserReg();
            return View(obj);
        }

        [HttpPost]
        public ActionResult Registration(users users)
        {

            //users users = shoppingPage.UserReg();

            String strConnString = ConfigurationManager.ConnectionStrings["EComm"].ConnectionString;
            SqlConnection con = new SqlConnection(strConnString);
            SqlCommand cmd = new SqlCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "sp_Add_User";
            cmd.Parameters.AddWithValue("@UserName", users.UserName);
            cmd.Parameters.AddWithValue("@Password", users.Password);
            cmd.Parameters.AddWithValue("@Email", users.Email);
            cmd.Parameters.AddWithValue("@RoleId", users.Role);
            cmd.Parameters.Add("@id", SqlDbType.Int).Direction = ParameterDirection.Output;
            cmd.Connection = con;
            try
            {
                con.Open();
                cmd.ExecuteNonQuery();
                string id = cmd.Parameters["@id"].Value.ToString();
                users.RoleList = shoppingPage.UserReg();
                ViewData["message"] = "The New User " + users.UserName + " has created successfully";
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                con.Close();
                con.Dispose();
            }
            return View(users);
        }

        
    }
}

ECommerce/Views/Site/AddProduct.cshtml
@model ECommerce.Models.shopping

@{
    ViewBag.Title = "AddProduct";
}

<h2>Add Product</h2>

@using (Html.BeginForm("AddProduct","Site",FormMethod.Post, new { enctype= "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Product, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Product, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" />
                @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
        @Html.ViewData["Message"]
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ECommerce/Views/Site/Checkout.cshtml
@model ECommerce.Models.shopping
@{
    ViewBag.Title = "Checkout";
}

<h2>Checkout</h2>

<div>
    @if (Session["Cart"] == null)
    {
        <div class="alert alert-danger">
            <strong>No Product Added</strong>
        </div>
    }
    else
    {
        <table>
            <thead>
                <tr>
                    <td>Product</td>
                    <td>Cost</td>
                    <td>Add</td>
                </tr>
            </thead>
            @foreach (var shoppping in List<> Session["Cart"])
            {
                <tbody>
                    <tr>
                        <td>@shoppping.Product</td>
                        <td>@shoppping.Cost</td>
                        <td>
                            <a href="@Url.Action("Add","AddToCart", new { ProductId= shoppping.ProductID , url="Checkout"})">
                                <i class="fa fa-plus"></i>
                            </a>
                        </td>
                    </tr>
                </tbody>
            }

        </table>
    }
</div>

ECommerce/Views/Site/Clothing.cshtml
@model ECommerce.Models.shopping

@{
    ViewBag.Title = "Clothing";
}

<h2>@Html.DisplayFor(model=>model.Product)</h2>


<div class="container-fluid">
    <div class="pull-left">
        <img src="@Url.Content(Model.Image)" style="width:300px; height:300px; border:solid" />
    </div>
    <div class="pull-left", style="margin-left:70px">
        <div>
            <h2>@Html.DisplayFor(model => model.Product)</h2>
            <h3>Description: @Html.DisplayFor(model => model.Description)</h3>
            <h3>Category : @Html.DisplayFor(model => model.Category)</h3>
            <h3>Cost :@Html.DisplayFor(model => model.Cost)</h3>
            <br />
            <div style="margin-left:0px">
                <a id="btn_add" href="@Url.Action("Add", "AddToCart", new { ID = Model.ID, Product = Model.Product, Image = Model.Image, Category = Model.Category, Description = Model.Description, Cost = Model.Cost })" class="btn btn-info btn-lg"style="margin-left:60px">
                    <span class="glyphicon glyphicon-shopping-cart"></span>Add To Cart
                </a>
            </div>
        </div>
    </div>    
</div>

ECommerce/Views/Site/Home.cshtml
@model IEnumerable<ECommerce.Models.shopping>

@{
    ViewBag.Title = "Home";
}

<div class="container">
    <h2 class="text-center">Product List</h2>
    @foreach (var shopping in Model)
    {
        <div class="col-md-4" style="border:2px solid black">
            <div style="text-align:center; border-bottom:2px solid maroon">
                <h3>@shopping.Product</h3>
            </div>

            <div>
                <div class="col-md-8">
                    <img src="@shopping.Image" width="150px" height="150px" />
                </div>
                <div class="col-md-4" style="text-align:left">
                    <b>@Html.ActionLink(shopping.Description, "Clothing", "Site", new { id = shopping.ID }, null)</b>
                </div>
            </div>

            <div class="col-md-12" style="font-size: 18px; border-top: 2px solid maroon; padding:2px">
                <b>@shopping.Cost.ToString(format: "#,##0.00 INR")</b>
            </div>
            <div class="col-md-12" style="text-align:right; margin-bottom: 10px; border-top:2px solid maroon; padding:2px">
                @*<input type="button" name="AddToCart" value="Add To Cart" class="btn-btn-primary" />*@
            </div>
        </div>
    }
</div>



 

ECommerce/Views/Site/Insert.cshtml
@model ECommerce.Models.shopping

@{
    ViewBag.Title = "Insert";
}

<h2>Insert</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>shopping</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Product, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ECommerce/Views/Site/Login.cshtml
@model ECommerce.Models.users
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

<div>
    @Html.ValidationSummary(false, null, new { @class = "text-danger" })
</div>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(x => x.UserName)
        @Html.TextBoxFor(x => x.UserName, new { @class = "form-control", autocomplete = "off" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.Password)
        @Html.TextBoxFor(x => x.Password, new { @class = "form-control", type = "password" })
    </div>
    <div class="form-group">
        <button id="CmdSubmit" type="submit" class="btn btn-success">Log In</button>
    </div>
}

<div>
    <h4 style="color:red">@Html.ViewData["Msg"]</h4>
</div>

<div>
    @Html.ActionLink("New User Registration", "Registration", null, new { @class = "btn btn-info" })
</div>

ECommerce/Views/Site/Registration.cshtml
@model ECommerce.Models.users

@{
    ViewBag.Title = "Registration";
}

<h2>Registration Form</h2>

@using (Html.BeginForm("Registration", "Site", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Role", Model.RoleList as IEnumerable<SelectListItem>,"Select Role")

                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
        @Html.ViewData["Message"]
    </div>
}

<div style="padding-left:193px">
    @Html.ActionLink("SignIn Page","Login", "Site", new { @class="btn btn-info"})
</div>

ECommerce/Views/Site/RoleList.cshtml
@model ECommerce.Models.users
@{
    ViewBag.Title = "RoleList";
}

<h2>RoleList</h2>

<div class="form-group">
    @Html.LabelFor(model => model.RoleList, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownList("Roles", Model.RoleList, "Select Role")

        @Html.ValidationMessageFor(model => model.RoleList, "", new { @class = "text-danger" })
    </div>
</div>